<ul id="ordering-controls">
  <li id="size">
    <select class="form-control">
      <option>Small</option>
      <option>Medium</option>
      <option>Large</option>
      <option>X-Large</option>
      <option>Fuckin Fat</option>
    </select>
  </li>
  <li>in</li>
  <li id="color">
    <select class="form-control">
      <option>Red</option>
      <option>Black</option>
      <option>Yellow</option>
      <option>Pink</option>
      <option>Shit Brown</option>
    </select>
  </li>
  <li><a href=""><i class="fa fa-info-circle"></i></a></li>
</ul>
