<div class="col-xs-12 col-sm-2 pull-right shop-sidebar">
    
          <aside id="product-categories">
      
            <h3>By Category</h3>
            <ul>
              <li><a href="">Lingerie</a> <span>(532)</span></li>
              <li><a href="">Furniture</a> <span>(532)</span></li>
              <li><a href="">Whips</a> <span>(532)</span></li>
              <li><a href="">Storage</a> <span>(532)</span></li>
            </ul>
      
          </aside>
    
          <aside id="product-colors">
      
            <h3>By Color</h3>
            <ul class="swatches">
              <li><a class="swatch-black" href=""></a></li>
              <li><a class="swatch-red" href=""></a></li>
              <li><a class="swatch-purple" href=""></a></li>
              <li><a class="swatch-blue" href=""></a></li>
              <li><a class="swatch-pink" href=""></a></li>
              <li><a class="swatch-yellow" href=""></a></li>
            </ul>
      
          </aside>
    
          <aside id="product-sizing">
      
            <h3>By Size</h3>
            <ul>
              <li><a href="">Small</a> <span>(532)</span></li>
              <li><a href="">Medium</a> <span>(532)</span></li>
              <li><a href="">Large</a> <span>(532)</span></li>
              <li><a href="">X-Large</a> <span>(532)</span></li>
              <li><a href="">Plus Sized</a> <span>(532)</span></li>
            </ul>
      
          </aside>
    
          <aside id="product-material">
      
            <h3>By Material</h3>
            <ul>
              <li><a href="">Nylon</a> <span>(532)</span></li>
              <li><a href="">Leather</a> <span>(532)</span></li>
              <li><a href="">Nylon</a> <span>(532)</span></li>
              <li><a href="">Lace</a> <span>(532)</span></li>      
            </ul>
      
          </aside>
    
        </div><!-- /.col-sm-12 /.col-lg-3 END Sidebar -->
