<?php
  
?>

   <footer class="mt60">
    <div class="container">
     <div class="col-sm-12 pt30 pb30 footer-helpful-links">

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Last Viewed Item</h3>
       
      </div><!-- END Last Viewed Item -->

     </div><!-- END Footer Helpful Links -->
    </div><!-- /.container -->

    <div class="row mt30 footer-copyright-wrapper">
     <div class="container">
      <div class="row">
       <div class="col-xs-12 col-lg-6">
        <p>All Content &copy; 2014 Syzygy by Devign, LLC.</p>
       </div>
      </div>
     </div><!-- /.container -->
    </div>

   </footer>

    <!-- ImagesLoaded -->
    <script src="<?=$config['full_url']?>frontend/themes/lib/forge/js/imagesloaded.pkgd.min.js"></script>
    <!-- Masonry -->
    <script src="<?=$config['full_url']?>frontend/themes/lib/forge/js/isotope.pkgd.js"></script>
    <!-- Shop Grid -->
    <script src="<?=$config['full_url']?>frontend/themes/lib/forge/js/shopgrid.js"></script>

  </body>
  </html>
