<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <meta name="description" content="<?= $template_data['page_description'] ? $template_data['page_description'] : ''?>">
 <title><?=$template_data['page_title']?></title>

 <!-- Google Fonts -->
 <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

 <!-- Font Awesome -->
 <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

 <!-- Bootstrap -->
 <link href="<?=$config['full_url'] . 'frontend/themes/'?>lib/forge/css/bootstrap.css" rel="stylesheet">

 <!-- Zen Theme Custom Styles -->
 <link href="<?=$config['full_url'] . 'frontend/themes/' . $config['theme'] . DSEP?>css/custom-styles.css" rel="stylesheet">

 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
 <!-- Include all compiled plugins (below), or include individual files as needed -->
 <script src="<?=$config['full_url'] . 'frontend/themes/'?>lib/forge/js/bootstrap.min.js"></script>
 <!-- Masonry -->
 <script src="<?=$config['full_url'] . 'frontend/themes/'?>lib/forge/js/masonry.pkgd.min.js"></script>

 <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
 <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

 </head>
 <body id="homepage">

  <header>
   <div class="container">
    <div class="row top-bar mt10 mb10">

     <div class="col-xs-12 col-md-6 pull-right">
      <ul class="helpful-links pull-right">
       <li>(701) 123-4567</li>
       <li>
        <ul class="socials">
         <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
         <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
         <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
         <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
        </ul>
       </li>
       <li ><a href="#">Help</a></li>
      </ul><!-- END Header Sub Menu -->
     </div><!-- /.col-sm-6 -->

     <div class="col-xs-12 col-md-6">
      <p>Welcome Guest, <a href="#">Sign In</a> or <a href="#">Sign Up</a>.</p>
     </div><!-- /.col-sm-6 -->

    </div><!-- /.row -->

    <div class="row mb15 pb15 masthead">

     <div class="col-xs-6 col-lg-4 logo-wrapper">
        
      <?php if (file_exists(THEME_PATH . 'images/logo.png')) : ?>
        <a href="home.phtml"><img title="Uptown Florist" src="<?=$config['full_url']?>frontend/themes/<?=$config['theme']?>/images/logo.png" alt="Uptown Florist" /></a>
      <?php else : ?>
        <a href="home.phtml"><h1>Syzygy Store</h1></a>
      <?php endif; ?>

      
      <!-- Store Logo if there's a logo uploaded -->

     </div><!-- /.col-sm-3 -->

     <div class="col-xs-6 col-lg-2 header-cart-wrapper">
      <div class="header-cart">
       <ul >
        <li><span>0</span> Items</li>
       </ul>
      </div>
     </div><!-- /.col-sm-9 -->

     <div class="col-xs-12 col-lg-6 search-wrapper">
      <div class="search">
       <form role="form">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Keyword or Item #">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
       </form>
      </div>
     </div><!-- /.col-sm-9 -->

    </div><!-- /.row -->

    <div class="row mb15">

<?php include 'menu.phtml'; ?>

     <div class="col-sm-12 col-lg-4 announcment">
      <p>Sale or info ticker. <a href="#">Hot new product</a> <strong>%50 OFF!</strong></p>
     </div>

    </div><!-- /.row -->

   </div><!-- /.container -->
  </header><!-- /header -->