<?php 
$template_data = [
                    'page_title' => 'Syzygy Home',
                    'page_description' => 'Syzygy ecommerce home page.'
];

include 'header.phtml'; 

?>

  <section id="homepage-slider" class="mt30 mb30">
   <div class="container">
    <div class="row">

     <div class="col-sm-12 col-lg-12">

      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
       <!-- Indicators -->
       <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
       </ol>

       <!-- Wrapper for slides -->
       <div class="carousel-inner">
        <div class="item active">
         <img src="<?=$config['full_url'] . 'frontend/themes/' . $config['theme'] . DSEP?>images/syzygy-zen-banner.jpg" alt="Syzygy Zen">
        </div>
        <div class="item">
         <img src="<?=$config['full_url'] . 'frontend/themes/' . $config['theme'] . DSEP?>images/syzygy-sexy-back-banner.jpg" alt="...">
         </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
       </div>

      </div><!-- END Slider Container -->

     </div><!-- /.row -->
    </div><!-- /.container -->
   </section>

   <section class="homepage-calls-to-action">
    <div class="container">
     <div class="row">

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->


     </div><!-- /.row -->
    </div><!-- /.container -->
   </section>

   <!-- Homepage Shop Grid -->
   <section class="container mt60 homepage-content">

    <h2>Shop our latest products!</h2>

    <div class="row">
            <div class="col-lg-12">
              
              <div id="shop-grid">
                <div class="grid-sizer"></div>
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst sale">
                      <span>Sale</span>
                    </div>

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/3-piece-web-of-seduction-teddy.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/hand-cuffs.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/basic-instict-panty-stocking.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/pink-chest.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/2-piece-charming-thong-stockings.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/rated-x-3-piece-racy-bodysuit.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper  w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst new-item">
                      <span>New</span>
                    </div>
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/sex-wedge.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/stretch-lace-bra-cutout-panty-set.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/pink-riding-crop.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="images/placeholders/800x1200-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
              </div><!-- /#shop-grid -->
              
            </div>
          </div>
   
   </section>
   <!-- END Homepage SHop Grid -->


  
<?php include 'footer.phtml'; ?>  