<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zen Theme - Syzygy</title>

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

  <!-- Font Awesome -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Bootstrap -->
  <link href="../forge/css/bootstrap.css" rel="stylesheet">

  <!-- Zen Theme Custom Styles -->
  <link href="assets/css/custom-styles.css" rel="stylesheet">

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../forge/js/bootstrap.min.js"></script>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body id="cart">

    <header>
      <div class="container">
        <div class="row top-bar mt10 mb10">

          <div class="col-xs-12 col-md-6 pull-right">
            <ul class="helpful-links pull-right">
              <li>(701) 123-4567</li>
              <li>
                <ul class="socials">
                  <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
              </li>
              <li ><a href="#">Help</a></li>
            </ul><!-- END Header Sub Menu -->
          </div><!-- /.col-sm-6 -->

          <div class="col-xs-12 col-md-6">
            <p>Welcome Guest, <a href="#">Sign In</a> or <a href="#">Sign Up</a>.</p>
          </div><!-- /.col-sm-6 -->

        </div><!-- /.row -->

        <div class="row mb15 pb15 masthead">

          <div class="col-xs-6 col-lg-4 logo-wrapper">
        
            <a href="index.phtml"><h1>Syzygy Store</h1></a>
            <!-- Store Title if there's no logo uploaded -->

            <!-- <a href="/"><img title="Zen Theme" src="assets/images/syzygy-zen-theme-logo.png" alt="Zen Theme" /></a>-->
            <!-- Store Logo if there's a logo uploaded -->

          </div><!-- /.col-sm-3 -->

          <div class="col-xs-6 col-lg-2 header-cart-wrapper">
            <div class="header-cart">
              <ul >
                <li><span>0</span> Items</li>
              </ul>
            </div>
          </div><!-- /.col-sm-9 -->

          <div class="col-xs-12 col-lg-6 search-wrapper">
            <div class="search">
              <form role="form">
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Keyword or Item #">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div><!-- /.col-sm-9 -->

        </div><!-- /.row -->

        <div class="row mb15">

          <div class="col-sm-12 col-lg-8 main-menu">

            <ul class="nav nav-pills">
              <li><a href="shop.phtml">Menu Item</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Dropdown <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Child Menu Item</a></li>
                </ul>
              </li>
              <li><a href="#">Menu Item</a></li>
            </ul>

          </div><!-- /.main-menu -->

          <div class="col-sm-12 col-lg-4 announcment">
            <p>Sale or info ticker. <a href="#">Hot new product</a> <strong>%50 OFF!</strong></p>
          </div>

        </div><!-- /.row -->

      </div><!-- /.container -->
    </header><!-- /header -->

    <div class="container">
 
      <div class="row">
        
        <div class="col-lg-10 col-lg-offset-1">
          
          <div class="row cart-content">
            
            <h1>Shopping Cart</h1>
            
            <div class="col-lg-12 cart-header-content">
              
              <!-- Cart Header -->
              <div class="row cart-header">
                <div class="col-lg-5 col-lg-offset-2">
                  <h3>Product</h3>
                </div>
                <div class="col-lg-2 align-center">
                  <h3>Quantity</h3>
                </div>
                <div class="col-lg-2 align-center">
                  <h3>Price</3>
                </div>
              </div>
              <!-- END Cart Header -->
              
              <!-- Cart Item -->
              <div class="row cart-item">
                <div class="col-lg-2">
                  <img title="Product Name." src="assets/images/placeholders/800x1200-placeholder.png" alt="Product Name." class="img-responsive" />
                </div><!-- END Thumbnail -->
                <div class="col-lg-5 cart-product-description">
                  <a href="">Pretty Awesome Product Title</a>
                  <ul>
                    <li><span>Item Price:</span> $44.95</li>
                    <li><span>SKU:</span> #696969</li>
                    <li><span>COLOR:</span> Black</li>
                    <li><span>Size:</span> Fucking Huge</li>
                  </ul>
                </div><!-- END Description -->
                <div class="col-lg-2 align-center pt10">
                  
                    <div class="form-group">
                      <input type="number" class="form-control" id="cart-quantity" value="2">
                    </div>
                    <button type="button" class="btn btn-default">Update</button>
                  
                </div><!-- END Quantity -->
                <div class="col-lg-2 cart-price align-center pt10">
                  <h2>$89.90</h2>
                </div><!-- END Price -->
                <div class="col-l-1 cart-remove align-center pt10">
                  <a href=""><i class="fa fa-minus-square"></i></a>
                </div><!-- END Remove Item -->
              </div>
              <!-- END Cart Item -->
              
            </div>
            
          </div><!-- /.cart-header -->
          
          <div class="row cart-footer pt15 pb15">
            
             <div class="col-lg-6">
               
               <div class="row">
                 
                 <div class="col-xs-9">
                   <div class="form-group">
                     <input type="text" class="form-control" id="coupon-code" placeholder="Coupon Code">
                   </div>
                 </div>
                 
                 <div class="col-xs-3">
                   <button type="submit" class="btn btn-default">Apply</button>
                 </div>
                 
               </div>
               
             </div><!-- Coupon Code -->
             
             <div class="col-lg-4 pull-right cart-totals">
               
               <ul>
                 <li>Cart Subtotal: $89.90</li>
                 <li>Shipping: $5.00</li>
                 <li class="cart-total">Total: $53.95</li>
               </ul>
               
              <button type="button" class="btn btn-default">Keep Shopping</button>
               
               <button type="button" class="btn btn-green btn-lg">Checkout</button>
               
               
             </div> <!-- Checkout -->
            
          </div>
          
        </div>
        
      </div>

    </div><!-- /.container -->
   
      <footer class="mt60">
        <div class="container">
          <div class="col-sm-12 pt30 pb30 footer-helpful-links">

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Last Viewed Item</h3>
      
            </div><!-- END Last Viewed Item -->

          </div><!-- END Footer Helpful Links -->
        </div><!-- /.container -->

        <div class="row mt30 footer-copyright-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-xs-12 col-lg-6">
                <p>All Content &copy; 2014 Syzygy by Devign, LLC.</p>
              </div>
            </div>
          </div><!-- /.container -->
        </div>

      </footer>

      <!-- Product Thumbnail Carousel -->
      <script src="../forge/js/productcarousel.js"></script>
      <!-- ImagesLoaded -->
      <script src="../forge/js/imagesloaded.pkgd.min.js"></script>
      <!-- Masonry -->
      <script src="../forge/js/isotope.pkgd.js"></script>
      <!-- Shop Grid -->
      <script src="../forge/js/shopgrid.js"></script>
      
    </body>
    </html>