<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zen Theme - Syzygy</title>

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

  <!-- Font Awesome -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Bootstrap -->
  <link href="../forge/css/bootstrap.css" rel="stylesheet">

  <!-- Zen Theme Custom Styles -->
  <link href="assets/css/custom-styles.css" rel="stylesheet">

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../forge/js/bootstrap.min.js"></script>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


  </head>
  <body id="checkout">
    
    <div class="container mt60">
      <div class="row">
    
        <div class="col-xs-10 col-xs-offset-1 checkout-wrapper">
          
          <header class="row">
            
            <div class="col-xs-12 align-center">
              <h1><i class="fa fa-bolt"></i> Easy Checkout</h1>
            </div>
            
          </header>
          
          <div class="row info-options-wrapper">
            
            <div id="billing-info" class="col-xs-6">
              
              <h2>Billing Info</h2>
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-5">
                    <input type="text" class="form-control" id="billing-user-first-name" placeholder="First Name">
                  </div>
                  <div class="col-xs-7">
                    <input type="text" class="form-control" id="billing-user-last-name" placeholder="Last Name">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="text" class="form-control" id="billing-company" placeholder="Company Name (Optional)">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="text" class="form-control" id="billing-address" placeholder="Address">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="text" class="form-control" id="billing-address-2" placeholder="Apt, Suite, Bldg. (Optional)">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-6">
                    <select class="form-control">
                      <option value="AL">Alabama</option>
                      <option value="AK">Alaska</option>
                      <option value="AZ">Arizona</option>
                      <option value="AR">Arkansas</option>
                      <option value="CA">California</option>
                      <option value="CO">Colorado</option>
                      <option value="CT">Connecticut</option>
                      <option value="DE">Delaware</option>
                      <option value="DC">District Of Columbia</option>
                      <option value="FL">Florida</option>
                      <option value="GA">Georgia</option>
                      <option value="HI">Hawaii</option>
                      <option value="ID">Idaho</option>
                      <option value="IL">Illinois</option>
                      <option value="IN">Indiana</option>
                      <option value="IA">Iowa</option>
                      <option value="KS">Kansas</option>
                      <option value="KY">Kentucky</option>
                      <option value="LA">Louisiana</option>
                      <option value="ME">Maine</option>
                      <option value="MD">Maryland</option>
                      <option value="MA">Massachusetts</option>
                      <option value="MI">Michigan</option>
                      <option value="MN">Minnesota</option>
                      <option value="MS">Mississippi</option>
                      <option value="MO">Missouri</option>
                      <option value="MT">Montana</option>
                      <option value="NE">Nebraska</option>
                      <option value="NV">Nevada</option>
                      <option value="NH">New Hampshire</option>
                      <option value="NJ">New Jersey</option>
                      <option value="NM">New Mexico</option>
                      <option value="NY">New York</option>
                      <option value="NC">North Carolina</option>
                      <option value="ND">North Dakota</option>
                      <option value="OH">Ohio</option>
                      <option value="OK">Oklahoma</option>
                      <option value="OR">Oregon</option>
                      <option value="PA">Pennsylvania</option>
                      <option value="RI">Rhode Island</option>
                      <option value="SC">South Carolina</option>
                      <option value="SD">South Dakota</option>
                      <option value="TN">Tennessee</option>
                      <option value="TX">Texas</option>
                      <option value="UT">Utah</option>
                      <option value="VT">Vermont</option>
                      <option value="VA">Virginia</option>
                      <option value="WA">Washington</option>
                      <option value="WV">West Virginia</option>
                      <option value="WI">Wisconsin</option>
                      <option value="WY">Wyoming</option>
                    </select>
                  </div>
                  <div class="col-xs-6">
                    <input type="text" class="form-control" id="billing-zip" placeholder="ZIP / Postal Code">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="text" class="form-control" id="billing-city" placeholder="City">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="" data-toggle="collapse" data-target="#shipping-info">
                  Ship to a different shipping address.
                </label>
              </div>
              
              <div id="shipping-info" class="collapse">
                
                <h2>Shipping Info</h2>
              
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-5">
                      <input type="text" class="form-control" id="shipping-user-first-name" placeholder="First Name">
                    </div>
                    <div class="col-xs-7">
                      <input type="text" class="form-control" id="shipping-user-last-name" placeholder="Last Name">
                    </div>
                  </div><!-- /.row -->
                </div><!-- /.form-group -->
              
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-12">
                      <input type="text" class="form-control" id="shipping-company" placeholder="Company Name (Optional)">
                    </div>
                  </div><!-- /.row -->
                </div><!-- /.form-group -->
              
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-12">
                      <input type="text" class="form-control" id="shipping-address" placeholder="Address">
                    </div>
                  </div><!-- /.row -->
                </div><!-- /.form-group -->
              
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-12">
                      <input type="text" class="form-control" id="shipping-address-2" placeholder="Apt, Suite, Bldg. (Optional)">
                    </div>
                  </div><!-- /.row -->
                </div><!-- /.form-group -->
              
                <div class="form-group">
                  <div class="row">
                    <div class="col-xs-6">
                      <select class="form-control">
                        <option value="AL">Alabama</option>
                        <option value="AK">Alaska</option>
                        <option value="AZ">Arizona</option>
                        <option value="AR">Arkansas</option>
                        <option value="CA">California</option>
                        <option value="CO">Colorado</option>
                        <option value="CT">Connecticut</option>
                        <option value="DE">Delaware</option>
                        <option value="DC">District Of Columbia</option>
                        <option value="FL">Florida</option>
                        <option value="GA">Georgia</option>
                        <option value="HI">Hawaii</option>
                        <option value="ID">Idaho</option>
                        <option value="IL">Illinois</option>
                        <option value="IN">Indiana</option>
                        <option value="IA">Iowa</option>
                        <option value="KS">Kansas</option>
                        <option value="KY">Kentucky</option>
                        <option value="LA">Louisiana</option>
                        <option value="ME">Maine</option>
                        <option value="MD">Maryland</option>
                        <option value="MA">Massachusetts</option>
                        <option value="MI">Michigan</option>
                        <option value="MN">Minnesota</option>
                        <option value="MS">Mississippi</option>
                        <option value="MO">Missouri</option>
                        <option value="MT">Montana</option>
                        <option value="NE">Nebraska</option>
                        <option value="NV">Nevada</option>
                        <option value="NH">New Hampshire</option>
                        <option value="NJ">New Jersey</option>
                        <option value="NM">New Mexico</option>
                        <option value="NY">New York</option>
                        <option value="NC">North Carolina</option>
                        <option value="ND">North Dakota</option>
                        <option value="OH">Ohio</option>
                        <option value="OK">Oklahoma</option>
                        <option value="OR">Oregon</option>
                        <option value="PA">Pennsylvania</option>
                        <option value="RI">Rhode Island</option>
                        <option value="SC">South Carolina</option>
                        <option value="SD">South Dakota</option>
                        <option value="TN">Tennessee</option>
                        <option value="TX">Texas</option>
                        <option value="UT">Utah</option>
                        <option value="VT">Vermont</option>
                        <option value="VA">Virginia</option>
                        <option value="WA">Washington</option>
                        <option value="WV">West Virginia</option>
                        <option value="WI">Wisconsin</option>
                        <option value="WY">Wyoming</option>
                      </select>
                    </div>
                    <div class="col-xs-6">
                      <input type="text" class="form-control" id="shipping-zip" placeholder="ZIP / Postal Code">
                    </div>
                  </div><!-- /.row -->
                  
                </div><!-- /.form-group -->
                
                <hr />
                
              </div><!-- /.collapse -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="email" class="form-control" id="billing-email" placeholder="E-mail Address">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-12">
                    <input type="text" class="form-control" id="billing-telephone" placeholder="Telephone Number (555-555-5555)">
                  </div>
                </div><!-- /.row -->
              </div><!-- /.form-group -->
              
            </div><!-- /#billing-info -->
            
            <div id="payment-method" class="col-xs-6">
              
              <h2>Payment Method</h2>
              
              <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <div class="radio">
                        <label data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                          <input type="radio" name="payment-type" id="optionsRadios1" value="option1" >
                          Credit Card
                        </label>
                      </div>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                     
                     <div class="form-group">
                       <div class="row">
                         <div class="col-xs-5">
                           <select class="form-control">
                             <option>Card Type</option>
                             <option>American Express</option>
                             <option>MasterCard</option>
                             <option>Visa</option>
                             <option>Discover</option>
                           </select>
                         </div>
                         <div class="col-xs-7">
                           <input type="text" name="" class="form-control" id="payment-method-card-number" placeholder="Card #">
                         </div>
                       </div><!-- /.row -->
                     </div><!-- /.form-group -->
                     
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <div class="radio">
                        <label data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                          <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                          Paypal
                        </label>
                      </div>
                     </h4>
                  </div>
                  <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                      asdf
                    </div>
                  </div>
                </div>
                
              </div>
              
            </div>
            
          </div><!-- /.row -->
          
        </div><!-- /.checkout-wrapper -->
        
      </div><!-- /.row -->
    </div><!-- /.container -->
      
  </body>
  </html>