<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>Zen Theme - Syzygy</title>

 <!-- Google Fonts -->
 <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

 <!-- Font Awesome -->
 <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

 <!-- Bootstrap -->
 <link href="../forge/css/bootstrap.css" rel="stylesheet">

 <!-- Zen Theme Custom Styles -->
 <link href="assets/css/custom-styles.css" rel="stylesheet">

 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
 <!-- Include all compiled plugins (below), or include individual files as needed -->
 <script src="../forge/js/bootstrap.min.js"></script>
 <!-- Masonry -->
 <script src="../forge/js/masonry.pkgd.min.js"></script>

 <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
 <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

 </head>
 <body id="homepage">

  <header>
   <div class="container">
    <div class="row top-bar mt10 mb10">

     <div class="col-xs-12 col-md-6 pull-right">
      <ul class="helpful-links pull-right">
       <li>(701) 123-4567</li>
       <li>
        <ul class="socials">
         <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
         <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
         <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
         <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
        </ul>
       </li>
       <li ><a href="#">Help</a></li>
      </ul><!-- END Header Sub Menu -->
     </div><!-- /.col-sm-6 -->

     <div class="col-xs-12 col-md-6">
      <p>Welcome Guest, <a href="#">Sign In</a> or <a href="#">Sign Up</a>.</p>
     </div><!-- /.col-sm-6 -->

    </div><!-- /.row -->

    <div class="row mb15 pb15 masthead">

     <div class="col-xs-6 col-lg-4 logo-wrapper">
        
      <a href="index.phtml"><h1>Syzygy Store</h1></a>
      <!-- Store Title if there's no logo uploaded -->

      <!--<a href="/"><img title="Zen Theme" src="assets/images/syzygy-zen-theme-logo.png" alt="Zen Theme" /></a> -->
      <!-- Store Logo if there's a logo uploaded -->

     </div><!-- /.col-sm-3 -->

     <div class="col-xs-6 col-lg-2 header-cart-wrapper">
      <div class="header-cart">
       <ul >
        <li><span>0</span> Items</li>
       </ul>
      </div>
     </div><!-- /.col-sm-9 -->

     <div class="col-xs-12 col-lg-6 search-wrapper">
      <div class="search">
       <form role="form">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Keyword or Item #">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
       </form>
      </div>
     </div><!-- /.col-sm-9 -->

    </div><!-- /.row -->

    <div class="row mb15">

     <div class="col-sm-12 col-lg-8 main-menu">

      <ul class="nav nav-pills">
       <li><a href="shop.phtml">Menu Item</a></li>
       <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
         Dropdown <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
         <li><a href="#">Child Menu Item</a></li>
        </ul>
       </li>
       <li><a href="#">Menu Item</a></li>
      </ul>

     </div><!-- /.main-menu -->

     <div class="col-sm-12 col-lg-4 announcment">
      <p>Sale or info ticker. <a href="#">Hot new product</a> <strong>%50 OFF!</strong></p>
     </div>

    </div><!-- /.row -->

   </div><!-- /.container -->
  </header><!-- /header -->

  <section id="homepage-slider" class="mt30 mb30">
   <div class="container">
    <div class="row">

     <div class="col-sm-12 col-lg-12">

      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
       <!-- Indicators -->
       <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
       </ol>

       <!-- Wrapper for slides -->
       <div class="carousel-inner">
        <div class="item active">
         <img src="assets/images/syzygy-zen-banner.jpg" alt="Syzygy Zen">
        </div>
        <div class="item">
         <img src="assets/images/syzygy-sexy-back-banner.jpg" alt="...">
         </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
       </div>

      </div><!-- END Slider Container -->

     </div><!-- /.row -->
    </div><!-- /.container -->
   </section>

   <section class="homepage-calls-to-action">
    <div class="container">
     <div class="row">

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->

      <div class="col-sm-12 col-lg-4">
       <div class="call-to-action">

       </div>
      </div><!-- /.call-to-action -->


     </div><!-- /.row -->
    </div><!-- /.container -->
   </section>

   <!-- Homepage Shop Grid -->
   <section class="container mt60 homepage-content">

    <h2>Shop our latest products!</h2>

    <div class="row">
            <div class="col-lg-12">
              
              <div id="shop-grid">
                <div class="grid-sizer"></div>
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst sale">
                      <span>Sale</span>
                    </div>

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/3-piece-web-of-seduction-teddy.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/hand-cuffs.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/basic-instict-panty-stocking.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/pink-chest.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/2-piece-charming-thong-stockings.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/rated-x-3-piece-racy-bodysuit.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper  w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst new-item">
                      <span>New</span>
                    </div>
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/sex-wedge.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/stretch-lace-bra-cutout-panty-set.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/pink-riding-crop.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x1200-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
              </div><!-- /#shop-grid -->
              
            </div>
          </div>
   
   </section>
   <!-- END Homepage SHop Grid -->

   <footer class="mt60">
    <div class="container">
     <div class="col-sm-12 pt30 pb30 footer-helpful-links">

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Menu Heading</h3>
       <ul>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
        <li><a href="">Footer Link</a></li>
       </ul>
      </div><!-- END Helpful Links Column -->

      <div class="col-sm-12 col-lg-2">
       <h3>Last Viewed Item</h3>
       
      </div><!-- END Last Viewed Item -->

     </div><!-- END Footer Helpful Links -->
    </div><!-- /.container -->

    <div class="row mt30 footer-copyright-wrapper">
     <div class="container">
      <div class="row">
       <div class="col-xs-12 col-lg-6">
        <p>All Content &copy; 2014 Syzygy by Devign, LLC.</p>
       </div>
      </div>
     </div><!-- /.container -->
    </div>

   </footer>

    <!-- ImagesLoaded -->
    <script src="../forge/js/imagesloaded.pkgd.min.js"></script>
    <!-- Masonry -->
    <script src="../forge/js/isotope.pkgd.js"></script>
    <!-- Shop Grid -->
    <script src="../forge/js/shopgrid.js"></script>

  </body>
  </html>
  