<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zen Theme - Syzygy</title>

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

  <!-- Font Awesome -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Bootstrap -->
  <link href="../forge/css/bootstrap.css" rel="stylesheet">

  <!-- Zen Theme Custom Styles -->
  <link href="assets/css/custom-styles.css" rel="stylesheet">

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../forge/js/bootstrap.min.js"></script>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body id="product-page">

    <header>
      <div class="container">
        <div class="row top-bar mt10 mb10">

          <div class="col-xs-12 col-md-6 pull-right">
            <ul class="helpful-links pull-right">
              <li>(701) 123-4567</li>
              <li>
                <ul class="socials">
                  <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
              </li>
              <li ><a href="#">Help</a></li>
            </ul><!-- END Header Sub Menu -->
          </div><!-- /.col-sm-6 -->

          <div class="col-xs-12 col-md-6">
            <p>Welcome Guest, <a href="#">Sign In</a> or <a href="#">Sign Up</a>.</p>
          </div><!-- /.col-sm-6 -->

        </div><!-- /.row -->

        <div class="row mb15 pb15 masthead">

          <div class="col-xs-6 col-lg-4 logo-wrapper">
        
            <a href="index.phtml"><h1>Syzygy Store</h1></a>
            <!-- Store Title if there's no logo uploaded -->

            <!-- <a href="/"><img title="Zen Theme" src="assets/images/syzygy-zen-theme-logo.png" alt="Zen Theme" /></a>-->
            <!-- Store Logo if there's a logo uploaded -->

          </div><!-- /.col-sm-3 -->

          <div class="col-xs-6 col-lg-2 header-cart-wrapper">
            <div class="header-cart">
              <ul >
                <li><span>0</span> Items</li>
              </ul>
            </div>
          </div><!-- /.col-sm-9 -->

          <div class="col-xs-12 col-lg-6 search-wrapper">
            <div class="search">
              <form role="form">
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Keyword or Item #">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div><!-- /.col-sm-9 -->

        </div><!-- /.row -->

        <div class="row mb15">

          <div class="col-sm-12 col-lg-8 main-menu">

            <ul class="nav nav-pills">
              <li><a href="shop.phtml">Menu Item</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Dropdown <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Child Menu Item</a></li>
                </ul>
              </li>
              <li><a href="#">Menu Item</a></li>
            </ul>

          </div><!-- /.main-menu -->

          <div class="col-sm-12 col-lg-4 announcment">
            <p>Sale or info ticker. <a href="#">Hot new product</a> <strong>%50 OFF!</strong></p>
          </div>

        </div><!-- /.row -->

      </div><!-- /.container -->
    </header><!-- /header -->

    <div class="container" itemscope itemtype="http:schema.org/Product">
 
      <div id="product-header" class="row">
        <div class="col-lg-9 col-lg-offset-1">
          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Shop</a></li>
            <li><a href="#">Category</a></li>
            <li class="active">Pretty Awesome Product Name</li>
          </ol>
  
          <h1 itemprop="name">Pretty Awesome Product Name</h1>
  
          <ul>
            <li itemprop="brand" itemscope itemtype="http://schema.org/Organization">By <a href=""><span itemprop="name">Pretty Awesome Brand<span></a></li>
              <li>|</li>
              <li>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
                <i class="fa fa-star-o"></i>
              </li>
              <li><a href="">(15) Pretty Retarded Customer Reviews</a></li>
            </ul>
          
          </div>
        </div><!-- /.row /#product-header -->
      
        <div class="row mt30 product-wrapper">
        
          <div class="col-lg-4 media-wrapper">
          
            <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="false">
              <div class="carousel-inner">
                <div class="item active" data-thumb="0">
                  <img src="http://placehold.it/800x1200/555/fff&amp;text=Product+Main+1200+x+800">
                </div>
                <div class="item" data-thumb="0">
                  <img src="http://placehold.it/800x1200/00ffff/000&amp;text=Product+Image+2">
                </div>
                <div class="item" data-thumb="0">
                  <img src="http://placehold.it/800x1200/ff00ff/fff&amp;text=Product+Image+3">
                </div>
                <div class="item" data-thumb="0">
                  <img src="http://placehold.it/800x600/ffff00/000&amp;text=Product+Image+4+1200+x+600">
                </div>
                <div class="item" data-thumb="1">
                  <img src="http://placehold.it/800x1200/7B1C8E/fff&amp;text=Product+Image+5">
                </div>
                <div class="item" data-thumb="1">
                  <img src="http://placehold.it/800x1200/9EF383/000&amp;text=Product+Image+6">
                </div>
                <div class="item" data-thumb="1">
                  <img src="http://placehold.it/800x1200/D64908/fff&amp;text=Product+Image+7">
                </div>
                <div class="item" data-thumb="1">
                  <img src="http://placehold.it/800x1200/E3A3A1/000&amp;text=Product+Image+8">
                </div>
              </div>

            </div><!-- /#carousel --> 
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <div class="item active">
                    <div data-target="#carousel" data-slide-to="0" class="thumb"><img src="http://placehold.it/1200/555/fff&amp;text=Product+Main"></div>
                    <div data-target="#carousel" data-slide-to="1" class="thumb"><img src="http://placehold.it/100/00ffff/000&amp;text=Product+Image+2"></div>
                    <div data-target="#carousel" data-slide-to="2" class="thumb"><img src="http://placehold.it/100/ff00ff/fff&amp;text=Product+Image+3"></div>
                    <div data-target="#carousel" data-slide-to="3" class="thumb"><img src="http://placehold.it/100/ffff00/000&amp;text=Product+Image+4"></div>
                  </div><!-- /item -->
                  <div class="item">
                    <div data-target="#carousel" data-slide-to="4" class="thumb"><img src="http://placehold.it/100/612b65/fff&amp;text=Product+Image+5"></div>
                    <div data-target="#carousel" data-slide-to="5" class="thumb"><img src="http://placehold.it/100/00ffcc/000&amp;text=Product+Image+6"></div>
                    <div data-target="#carousel" data-slide-to="6" class="thumb"><img src="http://placehold.it/100/db371b/fff&amp;text=Product+Image+7"></div>
                    <div data-target="#carousel" data-slide-to="7" class="thumb"><img src="http://placehold.it/100/feb8aa/000&amp;text=Product+Image+8"></div>
                  </div><!-- /item -->
                </div><!-- /carousel-inner -->
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div> <!-- /thumbcarousel -->
            </div><!-- /clearfix -->
          
          </div><!-- /.col-lg-4 -->
        
          <div class="col-lg-6 product-details-wrapper">
          
            <ul id="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
              <li class="full-price" itemprop="price">
                $55.00
                <meta itemprop="price" content="55.00">
                <meta itemprop="propCurrency" content="USD" />
              </li>
              <li class="availability"><link itemprop="availability" href="http://www.schema.org/InStock" /><span class="in-stock">In stock</span></li>
            </ul>
            
            <ul id="ordering-controls">
              <li id="size">
                <select class="form-control">
                  <option>Small</option>
                  <option>Medium</option>
                  <option>Large</option>
                  <option>X-Large</option>
                  <option>Fuckin Fat</option>
                </select>
              </li>
              <li>in</li>
              <li id="color">
                <select class="form-control">
                  <option>Red</option>
                  <option>Black</option>
                  <option>Yellow</option>
                  <option>Pink</option>
                  <option>Shit Brown</option>
                </select>
              </li>
              <li><a href=""><i class="fa fa-info-circle"></i></a></li>
            </ul>
            
            <div id="short-description" itemprop="description">
              <p>Phasellus ac porta libero. Nullam tellus purus, facilisis at feugiat eget, tincidunt sit amet est. 
              Nunc viverra varius sem ut lacinia. Vestibulum diam metus, condimentum quis arcu in, venenatis consequat turpis. 
              Nam ultricies pulvinar felis quis euismod. Donec nec massa et est fringilla dignissim.</p>
            </div>
            
            <div class="row" id="add-to-cart-wrapper">
              <div class="col-xs-2">
                <select class="form-control">
                  <option>QTY.</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                  <option>6</option>
                  <option>7</option>
                  <option>8</option>
                  <option>9</option>
                  <option>10</option>
                  <option>Fucking Potatos</option>
                </select>
              </div><!-- END Quantity -->
              <div class="col-xs-5">
                <button type="button" class="btn btn-primary btn-lg btn-block"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
              </div>
              <div class="col-xs-5">
                <button type="button" class="btn btn-default btn-lg btn-block"><i class="fa fa-heart"></i> Add to Wishlist</button>
              </div>
            </div><!-- /.row /#add-to-cart-wrapper -->
            
            <ul id="product-meta-data">
              <li>SKU: <span>XJ9000</span></li>
              <li>Category: <a href="">Monkey</a></li>
              <li>Tags: <a href="">Poo Flinger</a>, <a href="">Magic Caster</a></li>
            </ul>
          
          </div><!-- END Product Controls /.col-xs-4 -->
        
          <div class="col-lg-2">
           
          </div><!-- END Last Viewed & Related /.col-xs-4 -->
        
        </div><!-- /.row /.product-wrapper -->
        
        <div class="row">
          
          <div class="col-lg-4">
            
            <div class="row">
            
              <div class="col-lg-12">
              
                <div class="video-container">
                  <iframe src="http://www.youtube.com/embed/dFVxGRekRSg" frameborder="0" width="560" height="315"></iframe>
                </div>
              
              </div><!-- /.row /.video-container -->
            
            </div>
            
          </div><!-- /.col-lg-4 -->
          
          <div class="col-lg-8">
            
            <div class="row">
              
              <div class="col-lg-12 product-long-description">
              
              <h2>Description</h2>
              
                <p>Phasellus ac porta libero. Nullam tellus purus, facilisis at feugiat eget, tincidunt sit amet est. Nunc viverra varius sem ut lacinia. Vestibulum diam metus, condimentum quis arcu in, venenatis consequat turpis. Nam ultricies pulvinar felis quis euismod. Donec nec massa et est fringilla dignissim. Cras id orci in est ultricies malesuada nec ut nibh. Nullam ac erat vitae nibh mollis euismod vel rutrum purus. In hac habitasse platea dictumst. Sed dolor orci, pulvinar ac lobortis sed, auctor sed ante.</p>
              
                <p>Morbi suscipit, ligula vitae lacinia vehicula, libero quam vestibulum velit, vitae gravida velit felis vitae nibh. Proin magna est, pellentesque vel efficitur sit amet, aliquet in dui. Nulla facilisi. Duis eu tristique nisi. Curabitur posuere eros sit amet suscipit dignissim. Aliquam quis aliquam orci. In non placerat diam. Nam non tellus accumsan odio venenatis auctor. Donec sem urna, dapibus nec rhoncus vel, viverra id nibh. Nulla a aliquam velit, non ornare leo. Sed ullamcorper at nibh nec maximus. Ut non augue pharetra, sodales justo pretium, cursus diam. Maecenas euismod lectus ac diam sodales, faucibus condimentum sapien posuere.</p>
              
              </div>
              
            </div><!-- /.row END Description -->
            
          </div><!-- /.col-lg-8 -->
          
        </div><!-- /.row -->

      </div><!-- /.container -->
   
      <footer class="mt60">
        <div class="container">
          <div class="col-sm-12 pt30 pb30 footer-helpful-links">

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Menu Heading</h3>
              <ul>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
                <li><a href="">Footer Link</a></li>
              </ul>
            </div><!-- END Helpful Links Column -->

            <div class="col-sm-12 col-lg-2">
              <h3>Last Viewed Item</h3>
      
            </div><!-- END Last Viewed Item -->

          </div><!-- END Footer Helpful Links -->
        </div><!-- /.container -->

        <div class="row mt30 footer-copyright-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-xs-12 col-lg-6">
                <p>All Content &copy; 2014 Syzygy by Devign, LLC.</p>
              </div>
            </div>
          </div><!-- /.container -->
        </div>

      </footer>

      <!-- Product Thumbnail Carousel -->
      <script src="../forge/js/productcarousel.js"></script>
      <!-- ImagesLoaded -->
      <script src="../forge/js/imagesloaded.pkgd.min.js"></script>
      <!-- Masonry -->
      <script src="../forge/js/isotope.pkgd.js"></script>
      <!-- Shop Grid -->
      <script src="../forge/js/shopgrid.js"></script>
      
    </body>
    </html>