<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zen Theme - Syzygy</title>

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,700' rel='stylesheet' type='text/css'>

  <!-- Font Awesome -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Bootstrap -->
  <link href="../forge/css/bootstrap.css" rel="stylesheet">

  <!-- Zen Theme Custom Styles -->
  <link href="assets/css/custom-styles.css" rel="stylesheet">

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../forge/js/bootstrap.min.js"></script>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body id="category">

    <header>
      <div class="container">
        <div class="row top-bar mt10 mb10">

          <div class="col-xs-12 col-md-6 pull-right">
            <ul class="helpful-links pull-right">
              <li>(701) 123-4567</li>
              <li>
                <ul class="socials">
                  <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                  <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
              </li>
              <li ><a href="#">Help</a></li>
            </ul><!-- END Header Sub Menu -->
          </div><!-- /.col-sm-6 -->

          <div class="col-xs-12 col-md-6">
            <p>Welcome Guest, <a href="#">Sign In</a> or <a href="#">Sign Up</a>.</p>
          </div><!-- /.col-sm-6 -->

        </div><!-- /.row -->

        <div class="row mb15 pb15 masthead">

          <div class="col-xs-6 col-lg-4 logo-wrapper">
        
            <a href="index.phtml"><h1>Syzygy Store</h1></a>
            <!-- Store Title if there's no logo uploaded -->

            <!-- <a href="/"><img title="Zen Theme" src="assets/images/syzygy-zen-theme-logo.png" alt="Zen Theme" /></a>-->
            <!-- Store Logo if there's a logo uploaded -->

          </div><!-- /.col-sm-3 -->

          <div class="col-xs-6 col-lg-2 header-cart-wrapper">
            <div class="header-cart">
              <ul >
                <li><span>0</span> Items</li>
              </ul>
            </div>
          </div><!-- /.col-sm-9 -->

          <div class="col-xs-12 col-lg-6 search-wrapper">
            <div class="search">
              <form role="form">
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Keyword or Item #">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div><!-- /.col-sm-9 -->

        </div><!-- /.row -->

        <div class="row mb15">

          <div class="col-sm-12 col-lg-8 main-menu">

            <ul class="nav nav-pills">
              <li><a href="shop.phtml">Menu Item</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Dropdown <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Child Menu Item</a></li>
                </ul>
              </li>
              <li><a href="#">Menu Item</a></li>
            </ul>

          </div><!-- /.main-menu -->

          <div class="col-sm-12 col-lg-4 announcment">
            <p>Sale or info ticker. <a href="#">Hot new product</a> <strong>%50 OFF!</strong></p>
          </div>

        </div><!-- /.row -->

      </div><!-- /.container -->
    </header><!-- /header -->

    <div class="container">
 
      <div id="category-header" class="row">
        <div class="col-lg-9 col-lg-offset-1">
          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Shop</a></li>
            <li class="active">Category</li>
          </ol>
  
          <h1>Category Name</h1>
  
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus blandit nunc est, nec ullamcorper ipsum pulvinar ornare. Cras malesuada purus ligula. Sed blandit cursus consequat. Ut cursus ultrices ex eu dapibus. Quisque libero sem, gravida sed pharetra vulputate, maximus in dui.</p>
        </div>
      </div><!-- /.row /#category-header -->
      <div class="row category-sort-wrapper">
        <div id="sort-by" class="col-lg-10">
    
          <label>Sort by</label> 
  
          <select class="form-control">
            <option>Relevance</option>
            <option>New Arrival</option>
            <option>Customer Rating</option>
            <option>Price: High to Low</option>
            <option>Price: Low to High</option>
          </select>
    
        </div>
        
        <div class="col-lg-2 narrow-choices">
        
          <h3>Narrow your choices</3>
        
        </div>
      </div><!-- /.row -->
      <div class="row">
        <div class="col-xs-12 col-sm-10 pull-left">

          <div class="row">
            <div class="col-lg-12">
              
              <div id="shop-grid">
                <div class="grid-sizer"></div>
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst sale">
                      <span>Sale</span>
                    </div>

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/3-piece-web-of-seduction-teddy.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/hand-cuffs.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/basic-instict-panty-stocking.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/pink-chest.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/2-piece-charming-thong-stockings.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/rated-x-3-piece-racy-bodysuit.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper  w2">
                  <div class="shop-item">
                    
                    <div class="shop-grid-burst new-item">
                      <span>New</span>
                    </div>
                    
                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/sex-wedge.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/stretch-lace-bra-cutout-panty-set.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/pink-riding-crop.jpg" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x600-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
                <!-- SHOP ITEM -->
                <div class="shop-item-wrapper">
                  <div class="shop-item">

                    <a title="Product Name." href="#">
                      <img title="Product Name." src="assets/images/placeholders/800x1200-placeholder.png" alt="Product Name." />
                    </a>

                    <a title="Brand" class="shop-item-brand" href="">G World Intimates</a>

                    <a href="#"><h3>2 Piece Charming Thong Stockings</h3></a>

                    <span>$999.99</span>
                  </div>
                </div>
                <!-- END SHOP ITEM -->
                
              </div><!-- /#shop-grid -->
              
            </div>
          </div>
          
        </div><!-- /.col-sm-12 .col-lg-9 -->
        
        <div class="col-xs-12 col-sm-2 pull-right shop-sidebar">
    
          <aside id="product-categories">
      
            <h3>By Category</h3>
            <ul>
              <li><a href="">Lingerie</a> <span>(532)</span></li>
              <li><a href="">Furniture</a> <span>(532)</span></li>
              <li><a href="">Whips</a> <span>(532)</span></li>
              <li><a href="">Storage</a> <span>(532)</span></li>
            </ul>
      
          </aside>
    
          <aside id="product-colors">
      
            <h3>By Color</h3>
            <ul class="swatches">
              <li><a class="swatch-black" href=""></a></li>
              <li><a class="swatch-red" href=""></a></li>
              <li><a class="swatch-purple" href=""></a></li>
              <li><a class="swatch-blue" href=""></a></li>
              <li><a class="swatch-pink" href=""></a></li>
              <li><a class="swatch-yellow" href=""></a></li>
            </ul>
      
          </aside>
    
          <aside id="product-sizing">
      
            <h3>By Size</h3>
            <ul>
              <li><a href="">Small</a> <span>(532)</span></li>
              <li><a href="">Medium</a> <span>(532)</span></li>
              <li><a href="">Large</a> <span>(532)</span></li>
              <li><a href="">X-Large</a> <span>(532)</span></li>
              <li><a href="">Plus Sized</a> <span>(532)</span></li>
            </ul>
      
          </aside>
    
          <aside id="product-material">
      
            <h3>By Material</h3>
            <ul>
              <li><a href="">Nylon</a> <span>(532)</span></li>
              <li><a href="">Leather</a> <span>(532)</span></li>
              <li><a href="">Nylon</a> <span>(532)</span></li>
              <li><a href="">Lace</a> <span>(532)</span></li>      
            </ul>
      
          </aside>
    
        </div><!-- /.col-sm-12 /.col-lg-3 END Sidebar -->
        
      </div><!-- /.row -->
  
      <div class="row pagination-wrapper">
        <ul class="pagination">
          <li><a href="#">&laquo;</a></li>
          <li><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li><a href="#">&raquo;</a></li>
        </ul>
      </div><!-- /.row END Pagination -->
  
      <div class="row category-content">
        <div class="col-lg-9 col-lg-offset-1">
          <h2>Category Subheading</h2>
    
          <p>Ut in ante ut dui mattis consectetur sit amet non mi. Praesent ac odio varius, feugiat libero at, euismod mauris. Aenean at nisl aliquet, condimentum tortor at, sodales odio. Donec neque erat, ultricies ac mi sed, tincidunt semper dui. Sed tincidunt ante malesuada, tincidunt risus sit amet, blandit urna. Etiam eu odio massa. In efficitur lorem at augue ornare, a venenatis ex vestibulum. Aenean tincidunt orci non lorem viverra consectetur. Vivamus ac dictum elit. Quisque aliquam orci id nunc cursus, eu volutpat odio cursus.</p>
    
        </div>
      </div>
  
    </div><!-- /.container -->



    <footer class="mt60">
      <div class="container">
        <div class="col-sm-12 pt30 pb30 footer-helpful-links">

          <div class="col-sm-12 col-lg-2">
            <h3>Menu Heading</h3>
            <ul>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
            </ul>
          </div><!-- END Helpful Links Column -->

          <div class="col-sm-12 col-lg-2">
            <h3>Menu Heading</h3>
            <ul>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
            </ul>
          </div><!-- END Helpful Links Column -->

          <div class="col-sm-12 col-lg-2">
            <h3>Menu Heading</h3>
            <ul>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
            </ul>
          </div><!-- END Helpful Links Column -->

          <div class="col-sm-12 col-lg-2">
            <h3>Menu Heading</h3>
            <ul>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
            </ul>
          </div><!-- END Helpful Links Column -->

          <div class="col-sm-12 col-lg-2">
            <h3>Menu Heading</h3>
            <ul>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
              <li><a href="">Footer Link</a></li>
            </ul>
          </div><!-- END Helpful Links Column -->

          <div class="col-sm-12 col-lg-2">
            <h3>Last Viewed Item</h3>
      
          </div><!-- END Last Viewed Item -->

        </div><!-- END Footer Helpful Links -->
      </div><!-- /.container -->

      <div class="row mt30 footer-copyright-wrapper">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-lg-6">
              <p>All Content &copy; 2014 Syzygy by Devign, LLC.</p>
            </div>
          </div>
        </div><!-- /.container -->
      </div>

    </footer>

    <!-- ImagesLoaded -->
    <script src="../forge/js/imagesloaded.pkgd.min.js"></script>
    <!-- Masonry -->
    <script src="../forge/js/isotope.pkgd.js"></script>
    <!-- Shop Grid -->
    <script src="../forge/js/shopgrid.js"></script>

  </body>
  </html>