<?php

$main_stmt = $db->prepare("SELECT SQL_CALC_FOUND_ROWS order_id, order_date, last_name
                        FROM orders
                        LEFT JOIN customers USING(customer_id)
                        LIMIT $start, $end");
$main_stmt->execute();
$result = $main_stmt->get_result();

?>
           <div class="col-xs-12 col-md-9">
             
            <section id="page-header">

              <div id="searchCriteria" style="float:right;">
              <form name="searchForm" action="customers.php" method="post">
              <input type="hidden" name="action" value="search">
              <span class="inputLabel">SEARCH: <input type="text" name="search_value" value="" size="20">

              <button class="button" onClick="searchForm.submit();">GO!</button>

              </form>
              </div>
              <h1><span class="glyphicon glyphicon-shopping-cart"></span> Orders :: View</h1>
              </section>

            <section id="content">
                <div id="actionNavContainer">
                    <ul id="actionNav">
                    <li><a href="/control/order/create">Create New Order</a></li>
                    </ul>
                </div>


    	<div style="padding-top:20px">
                <form name="productsForm" method="post" action="products.php">
        <input type="hidden" name="cid" value="">
      	<table class="detailsList">
      		<tr><th>ORDER ID</th><th>DATE</th><th>CUSTOMER NAME</th></tr>

      	<?php while ($row = $result->fetch_object()) : ?>
      		<tr onClick="document.productsForm.pid.value='<?= $row->order_id ?>';document.customersForm.submit()">
      		<td><a href="/control/product/edit/simple?sku=<?= $row->order_id ?>"><?= $row->order_id ?></a></td>
      		<td><?= $row->order_date ?></td><td><?= $row->last_name ?></td></tr>
      	<?php endwhile ?>

      	</table>
                </form>
    	</div>

<?php
/**
* GET TOTAL ROWS RETURNED AND CREATE PAGINATION
* 
* @var mysqli
*/
$result->close();
$result = $db->query("SELECT FOUND_ROWS() AS total");
$total_items = $result->fetch_object();    

$paginate = new Paginate($total_items->total, $current_page, $route[1]);

include 'paginate.phtml';   
?>


            </section>

          </div><!-- /.col-sm-12 /.col-lg-9 -->