<?php if (count($error_msg) > 0): ?>
    <div class="error">
        <?php foreach($error_msg as $err): ?>
        <div><?= $err ?></div>
        <?php endforeach; ?>
    </div>   
<?php elseif ($success_message): ?>
    <div class="success">
        <?= $success_message?>
    </div>
<?php endif; ?>

          <div class="col-xs-12 col-md-9">
             
            <section id="page-header">

              <div id="searchCriteria" style="float:right;">
              <form name="searchForm" action="customers.php" method="post">
              <input type="hidden" name="action" value="search">
              <span class="inputLabel">SEARCH: <input type="text" name="search_value" value="" size="20">

              <button class="button" onClick="searchForm.submit();">GO!</button>

              </form>
              </div>
              <h1><span class="glyphicon glyphicon-shopping-cart"></span> Page:: Edit</h1>
              </section>

            <section id="content">
                <div id="actionNavContainer">

                </div>

            




<div>
	<div style="padding-top:40px">
		<form name="productNew" method="post" enctype="multipart/form-data">
        <input type="hidden" name="form_action" value="update" />
        <table>
         <tr><td><label>Name:</label></td><td><input type="text" name="page_name" value="<?=$page->page_name?>" onBlur="autoSEOInput(this.value, this.form)"/> </td></tr>
         
        <tr><td><label>Title:</label></td><td><input type="text" name="page_title" value="<?=$page->page_title?>" onBlur="autoSEOInput(this.value, this.form)"/> </td></tr>
        
        <tr><td><label>URL:</label></td><td><input type="text" name="page_url" value="<?=$page->page_url?>"/></td></tr>
        
        <tr><td><label>Description:</label></td><td><textarea name="page_description" rows="10" cols="80"><?=$page->page_description?></textarea></td></tr>

        <tr><td><label>Keywords:</label></td><td><textarea name="page_keywords" rows="5" cols="80"><?=$page->page_keywords?></textarea></td></tr>
        
        <tr><td><label>Content:</label></td><td>
        <textarea class="mce" name="page_keywords" rows="20" cols="80"><?=$page->page_content?></textarea></td></tr>
  
          
        
        </table>
        <input type="submit" value="Save">
        </form>
	</div>

</div>



            </section>

          </div><!-- /.col-sm-12 /.col-lg-9 -->