<?php
require_once('functions.php');

?>

<div class="col-xs-12 col-md-9">
 
    <section id="page-header">

      <h1><span class="glyphicon glyphicon-file"></span> Pages :: Create New</h1>

    </section>

    <section id="content">
                

        <div>
	        <div style="padding:20px">

		        <form name="userNew" method="post" action="/control/page/list">
		        <input type="hidden" name="form_action" value="save">


	        <?php
		        createInputForm('cms_pages', array('page_id'));
	        ?>

		        </form>
	        </div>

        </div>

    </section>

</div><!-- /.col-sm-12 /.col-lg-9 -->
