<?php

$pages_query = "SELECT * FROM cms_pages WHERE store_id = " . $_COOKIE['SYZYGY_STOREID'];

$pages_stmt = $db->query($pages_query);

?>

          <div class="col-xs-12 col-md-9">
             
            <section id="page-header">

              <div id="searchCriteria" style="float:right;">
              <form name="searchForm" action="customers.php" method="post">
              <input type="hidden" name="action" value="search">
              <span class="inputLabel">SEARCH: <input type="text" name="search_value" value="" size="20">

              <button class="button" onClick="searchForm.submit();">GO!</button>

              </form>
              </div>
              <h1><span class="glyphicon glyphicon-file"></span> Pages :: View</h1>
              </section>

            <section id="content">
                <div id="actionNavContainer">
                    <ul id="actionNav">
                    <li><a href="/control/pages/create">Add Page</a></li>

                    </ul>
                </div>


	<div style="padding-top:20px">
	<table border="0" id="pagesTable" cellpadding="0" cellspacing="0">
	<tr><th></th><th>ID</th><th>Name</th></tr>
	<?php while ($result = $pages_stmt->fetch_object()) : ?>
		<tr>
		<td valign="center"><a onMouseOver="$(this).parents('tr').css('background-color', '#F2B7B2')"
		          onMouseOut="$(this).parents('tr').css('background-color', '#FFF')" class="miniButton" href="/control/users/edit/<?= $result->user_id?>">Edit</a></td>
		<td><?= $result->page_id ?></td>
		<td><?= $result->page_name ?></td>

		</tr>
	<?php endwhile ?>
	</table>
	</div>





            </section>

          </div><!-- /.col-sm-12 /.col-lg-9 -->

