<?php
    
?>
          <div class="col-xs-12 col-md-9">
             
            <section id="page-header">

              <div id="searchCriteria" style="float:right;">
              <form name="searchForm" action="customers.php" method="post">
              <input type="hidden" name="action" value="search">
              <span class="inputLabel">SEARCH: <input type="text" name="search_value" value="" size="20">

              <button class="button" onClick="searchForm.submit();">GO!</button>

              </form>
              </div>
              <h1><span class="glyphicon glyphicon-shopping-cart"></span> Products :: Add New</h1>
              </section>

            <section id="content">
                <div id="actionNavContainer">
                    <ul id="actionNav">
                    <li><strong>Simple</strong></li>
                    <li><a href="/control/product/create/variable">Variable</a></li>
                    <li><a href="/control/product/create/customizable">Customizable</a></li>
                    <li><a href="/control/product/create/virtual">Virtual</a></li>
                    </ul>
                </div>

            
<?php if (isset($_POST['formAction']) && $_POST['formAction'] == 'save') : ?>

<?php 
    $sku                = Utility::prepareData(Utility::sanitizeData($_POST['sku']));
    $brand_id           = $_POST['brand_id'];
    $name               = Utility::prepareData(Utility::sanitizeData($_POST['name']));
    $description        = Utility::prepareData(Utility::sanitizeData($_POST['description']));
    $short_description  = Utility::prepareData(Utility::sanitizeData($_POST['short_description']));
    $features           = Utility::prepareData(Utility::sanitizeData($_POST['features']));
    $price              = $_POST['price'];
    $weight             = $_POST['weight'];
    $vendor_id          = $_POST['vendor_id'];
    $categories         = $_POST['category'];
    $store_id           = $_COOKIE['SYZYGY_STOREID'];
    $product_url        = Utility::prepareData(Utility::sanitizeData($_POST['product_url']));
    $page_title         = Utility::prepareData(Utility::sanitizeData($_POST['page_title']));
    $keywords           = Utility::prepareData(Utility::sanitizeData($_POST['keywords']));
    $product_type       = $_POST['product_type'];
    $featured           = isset($_POST['featured']) ? $_POST['featured'] : 0;
    $onsale             = isset($_POST['onsale']) ? $_POST['onsale'] : 0;
    $sale_price         = $onsale ? $_POST['sale_price'] : 0;
    $media_tmpname      = $_FILES['mediafile']['tmp_name'];
    $media_customname   = Utility::sanitizeFilename($_POST['custom_filename']);
    $media_type         = $_POST['media_type'];
    

    
    $db->query("INSERT INTO products(sku,brand_id,name,description,price,weight,status,product_type,
            short_description,features,product_url,page_title,featured,onsale,sale_price)
            VALUES('$sku',$brand_id,'$name','$description','$price','$weight',1,'$product_type',
            '$short_description','$features','$product_url','$page_title','$featured','$onsale','$sale_price')");

    $db->query("INSERT INTO product_to_vendor(sku,vend_id) VALUES('$sku',$vendor_id)");
    
    $db->query("INSERT INTO product_to_store(sku,store_id) VALUES('$sku',$store_id)");  
    
    foreach ($categories as $k => $v) {
        $db->query("INSERT INTO product_to_category(sku,category_id) VALUES('$sku',$v)");    
    }

    /* SAVE PRODCUT MEDIA FILE */
    if (isset($media_tmpname) && $media_tmpname != null) {

        $media_customname = Utility::sanitizeFilename($_POST['custom_filename']);
        $media_type = $_POST['media_type'];
        $media_alt = isset($_POST['media_alt']) ? $_POST['media_alt'] : '';
        $media_url = 'media/' . $media_type . DSEP . $brand_id;
        
        if (false === $new_file = Utility::saveMediaFile($media_tmpname, $media_customname, $media_type, $brand_id)) {
            $error_msg[] = "Can't save $media_tmpname $media_type media file.";
        }  else {
            $result = $db->query("SELECT max(product_media_num) + 1 FROM product_media WHERE sku = '$sku'");
            $tmp = $result->fetch_row();
            if (empty($tmp[0])) {
                $next_num = 1;
            } else {
                $next_num = $tmp[0];
            }
            $result->close();
            $db->query("INSERT INTO product_media(sku,product_media_num,product_media_type,product_media_name,
                        product_media_filepath,product_media_url,product_media_alt)
                        VALUES('$sku','$next_num','$media_type','$new_file[1]','$new_file[0]','$media_url',
                        '$media_alt')");
            
        }

    }
                                                       
?>

<div style="padding-top:100px">
	<h3>PRODUCT SUCCESSFULLY ADDED</h3>
</div>


<?php else : ?>

<?php
    $brands = Utility::getSetValues($params = array('brand_id', 'brand_name', 'product_brands'));
    
    $vendors  = Utility::getSetValues($params = array('vendor_id', 'name', 'vendors'));
    

    
?>
<div>
	<div style="padding-top:40px">
		<form name="productNew" action="/control/product/create/simple" method="post" enctype="multipart/form-data">
		<input type="hidden" name="formAction" value="save">
        <input type="hidden" name="product_type" value="SIMPLE">

        <table>
        <tr><td><label>SKU:</label></td><td><input type="text" name="sku" value="" /></td></tr>
        <tr><td><label>Status:</label></td>
        <td><select name="status">
        <option value="1">Active</option>
        <option value="0">Inactive</option>
        </select></td></tr>
        <tr><td><label>Brand:</label></td><td><select name="brand_id">
        <?php foreach ($brands as $id => $name) : ?>
        <option value="<?= $id ?>"><?= $name ?></option>
        <?php endforeach; ?>
        </select>  </td></tr>
		
        <tr><td><label>Name:</label></td><td><input type="text" name="name" value="" onBlur="autoSEOInput(this.value, this.form)"/> </td></tr>
        
        <tr><td><label>Description:</label></td><td><textarea name="description" rows="10" cols="80"></textarea></td></tr>
        
        <tr><td><label>Short Description:</label></td><td><textarea name="short_description" rows="5" cols="80"></textarea></td></tr>
        
        <tr><td><label>Features:</label></td><td><textarea name="features" rows="5" cols="40"></textarea></td></tr>
        
        <tr><td><label>Price:</label></td><td><input type="text" name="price" value="" /></td></tr>
        <tr><td><label>On Sale:</label></td><td><input type="checkbox" name="onsale" value="1"></td></tr>
        <tr><td><label>Sale Price:</label></td><td><input type="text" name="sale_price" value="" /></td></tr>
        <tr><td><label>Weight:</label></td><td><input type="text" name="weight" value="" /></td></tr>
        <tr><td><label>Featured:</label></td><td><input type="checkbox" name="featured" value="1"></td></tr>
        <tr><td><label>Vendor:</label></td><td><select name="vendor_id">
        <?php foreach ($vendors as $id => $name) : ?>
        <option value="<?= $id ?>"><?= $name ?></option>
        <?php endforeach; ?>
        </select>  </td></tr>
        
        <tr><td><label>Category:</label></td>
        <td><?php printCategoryList(); ?></td></tr>  
          
        <tr><td><h3>SEO MAGIC</h3></td></tr>
        <tr><td><label>Page Title:</label></td>
        <td><input type="text" name="page_title" value="" size="80"/></td></tr>   
        <tr><td><label>Custom URL:</label></td>
        <td><input type="text" name="product_url" value="" size="80"/></td></tr>     
        <tr><td><label>Keywords:</label></td>
        <td><textarea name="keywords" rows="5" cols="30"></textarea></td></tr>
        </table>
        
        <table id="media-magic">
        <tr><td><h3>MEDIA MAGIC</h3></td></tr>
        <tr><td><label>File:</label></td>
        <td><input type="file" name="mediafile" /></td></tr>     
        <tr><td><label>Media Type:</label></td>
        <td><select name="media_type">
        <option value="IMAGE">Image</option>
        <option value="VIDEO">Video</option>
        <option value="PDF">PDF</option>
        </td></tr>   

        <tr><td><label>Custom Filename:</label></td>
        <td><input type="text" name="custom_filename" value="" /></td></tr>
        <tr><td><label>Alt Tag:</label></td>
        <td><input type="text" name="media_alt" value="" /></td></tr>
        </table>
        <input type="submit" value="Save">
        </form>
	</div>

</div>

<?php endif ?>

            </section>

          </div><!-- /.col-sm-12 /.col-lg-9 -->